
import type { Metadata } from "next";
import "./globals.css";
import Navbarmain from "@/components/Navbarmain";

export const metadata: Metadata = {
  title: "Grudhra Agency ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className=' '>
      
       <Navbarmain/>
        {children}
        
        </body>
    </html>
  );
}
